handle: stripe
isFrontendEnabled: $STRIPE_ENABLED
name: Stripe
paymentType: purchase
settings:
  apiKey: $STRIPE_SECRET_KEY
  publishableKey: $STRIPE_PUB_KEY
  sendReceiptEmail: $STRIPE_SEND_EMAIL
  signingSecret: ''
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
