#import "./fragments/FieldContentBlocks.gql"

query EntryFourOhFour {
  entry(section: "fourOhFour") {
    ... on fourOhFour_fourOhFour_Entry {
      id
      heading
      contentBlocks {
        ...FieldContentBlocks
      }
    }
  }
}
