#import "./fragments/FieldContentBlocks.gql"
#import "./fragments/AssetImages.gql"

query EntryHome {
    entry(section: "home") {
        title
        uri
        slug
        language
        typeHandle
        sectionHandle
        seomatic(asArray: true) {
            metaScriptContainer
            metaTitleContainer
            metaTagContainer
            metaJsonLdContainer
            metaLinkContainer
        }
        ... on home_home_Entry {
            heading
            image {
                ...Images
            }
            summary
            contentBlocks {
                ...FieldContentBlocks
            }
            previewImage {
                ...Images
            }
            previewText
            keywords
        }
    }
}
