fieldLayouts:
  0911386a-a6ae-463f-b98f-6c7c6ab90908:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 165f6069-538d-4c7e-8100-243afba8b5d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f2c6c9a-3092-47f2-b0dc-46d8ce11c178 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ba56093-6385-4f62-a57b-7c61f605137d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8aa229ec-7643-48c3-947d-9d2c1882b8f2 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b6a7aaf-ee96-4307-bb12-9cb50c92e93e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1a271ef6-b5fa-4971-a961-ea9317ca9310
        userCondition: null
handle: fourOhFour
hasTitleField: false
name: '404'
section: 5b4d305d-9ee5-46c8-a0ce-b6d10322743b # 404
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
