defaultPlacement: end
fieldLayouts:
  4ecf4e1d-8b68-4e78-b16b-d6c3cc9a78c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 40cd8982-a8ef-4dda-955a-067f9fc8727d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41c288bf-41f9-4a0c-95c3-3ef3c78051e6
        userCondition: null
handle: productCategories
name: 'Product Categories'
siteSettings:
  f8a2a825-4c38-46e8-853b-b3ee5d46969b: # Foster Commerce Dot All 2022
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 1c741add-2650-4095-a422-47bd2ba29393
