columnSuffix: null
contentColumnType: string
fieldGroup: 652c2871-27c1-4b30-8190-0a05255eb19b # Relations
handle: categories
instructions: null
name: Categories
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:1b753347-9223-47d6-8349-fc1c7c290ea1' # Product Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
