columnSuffix: qeshyjtt
contentColumnType: text
fieldGroup: 1b39f5a2-15c0-4af0-be7c-0735aba76665 # Text
handle: previewText
instructions: null
name: 'Preview Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
