columnSuffix: null
contentColumnType: string
fieldGroup: dee4f4f1-d8b0-4f5c-a6ff-b5f10e5a577f # Compound
handle: primaryNavigation
instructions: null
name: 'Primary Navigation'
searchable: false
settings:
  contentTable: '{{%matrixcontent_primarynavigation}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
