tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 70426368-62a0-4420-9d69-1d8d1cb50612
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\FullNameField
        uid: 9ac9abcc-a5d0-485e-b9f5-bb78dea62335
        userCondition: null
        warning: null
        width: 100
      -
        attribute: organization
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\OrganizationField
        uid: 74a90b5d-7642-4ab8-8e07-665cbdc48fdf
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 93e97a19-5470-4212-8952-a18a1335a4b7
        userCondition: null
        warning: null
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: b48f6e00-4d6e-4788-a9cd-7cc561e1be93
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 47da4e3a-321f-4791-b5a4-55045833cfa7 # Phone
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 8078faf0-8d18-438b-9e71-3fc8aadccc91
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\commerce\fieldlayoutelements\UserAddressSettings
        uid: 9d6503c5-f838-410c-983a-f12e48b4da57
        userCondition: null
        warning: null
    name: Content
    uid: 787b3ca7-9e1b-4a02-a89a-2bd074638529
    userCondition: null
