# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE services
# to expose port `5173` of DDEV's web container.
version: '3.6'
services:
  web:
    expose:
      - '5173'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,5174:5173
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,5173:5173